### ISSUE TITLE
Use of Sketchy with a Proxy - Error <URI::InvalidURIError: bad URI(is not URI?): 127.0.0.1:3128> in Scumbler

### ISSUE THREAD

**Issue by mrflibbleoz** [Netflix/Scumblr#49]
We are attempting to setup Sketchy to operate within a proxied environment.  The option '--proxy=https://127.0.0.1:3128' has been added to controllers/tasks.py. This all seems to operate perfectly fine when running Sketchy.

When trying to use the integration between Scumblr and sketchy however we receive the following error in the sidekiq.log. I am guessing adding the proxy variable to the tasks.py file has messed up the URL parsing?

2015-06-22T04:27:10Z 1864 TID-ovuk3c9ec ScreenshotRunner JID-6ec3e83bff2e5598f7826357 ERROR: Error communicating with sketchy: #<URI::InvalidURIError: bad URI(is not URI?): 127.0.0.1:3128> bad URI(is not URI?): 127.0.0.1:3128: ["/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/uri/common.rb:176:in `split'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/uri/common.rb:211:in `parse'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/uri/common.rb:747:in `parse'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/uri/generic.rb:1672:in `find_proxy'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/net/http.rb:1027:in `proxy_uri'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/net/http.rb:1014:in `proxy?'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/net/http.rb:868:in `connect'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/net/http.rb:862:in `do_start'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/net/http.rb:851:in `start'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/2.0.0/net/http.rb:1367:in `request'", "/home/threat-account/Scumblr/app/models/result.rb:102:in `create_attachment_from_sketchy'", "/home/threat-account/Scumblr/app/workers/screenshot_runner.rb:36:in `block in perform'", "/home/threat-account/Scumblr/app/workers/screenshot_runner.rb:29:in `each'", "/home/threat-account/Scumblr/app/workers/screenshot_runner.rb:29:in `perform'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:122:in `call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-status-0.5.0/lib/sidekiq-status/server_middleware.rb:37:in `call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/server/active_record.rb:6:in `call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/logging.rb:22:in `with_context'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/server/logging.rb:7:in `call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:127:in `call'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/middleware/chain.rb:127:in `invoke'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/processor.rb:51:in `block in process'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/processor.rb:94:in `stats'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/sidekiq-3.0.2/lib/sidekiq/processor.rb:50:in `process'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'", "/home/threat-account/.rbenv/versions/2.0.0-p481/lib/ruby/gems/2.0.0/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'"]
2015-06-22T04:27:10Z 1864 TID-ovuk3c9ec ScreenshotRunner JID-6ec3e83bff2e5598f7826357 INFO: done: 0.215 sec

**Comment by mrflibbleoz** [comment]
Apologies, it appears its not this line that is causing the issue but the proxy settings that are set within the linux environment itself.  Changed to export http_proxy="http://127.0.0.1:3128" and now don't get this error any longer.
